### ISSUE TITLE
Problem dumping ArrayObjects in php 7.2.8

### ISSUE THREAD

**Issue by mijohansen** [apioo/psx-schema#14] opened 2018-08-04 10:10 UTC
Hi, Christoph

Just discovered your framework and I'm working **psx/model** it into an extension for Slim Framework. Just using the Swagger model by now. 

Found that `PSX\Schema\Parser\Popo\Dumper` doesn't really create JSON for me as expected. I think also your test would fail too, but was not able to execute the tests when executing them on your repo. Anyway. Seem to fail on the "Paths" ArrayObject.

```JSON
{
    "swagger": "2.0",
    "host": "localhost",
    "basePath": "\/",
    "schemes": ["http"],
    "consumes": ["application\/json"],
    "produces": ["application\/json"],
    "paths": {
        "\/": {},
        "\/resource": {},
        "\/routes": {},
        "\/swagger.json": {}
    },
    "definitions": {}
}
````

I fixed it for now with this function, not a beauty, but it works for me:

```PHP
use PSX\Schema\Parser\Popo\Dumper;

class Util {

    /**
     * Utility class to solve
     *
     * @param $mixed
     * @return mixed
     */
    static public function dump($mixed) {
        static $dumper;
        if (is_null($dumper)) {
            $dumper = new Dumper();
        }
        $dumped = $dumper->dump($mixed);
        if(is_iterable($dumped)){
            foreach ($dumped as $prop => $value) {
                if(is_a($value, "ArrayObject")){
                    $new_array = [];
                    foreach ($value->getArrayCopy() as $value=>$element){
                        $new_array[$value] = self::dump($element);
                    }
                    $dumped[$prop] = $new_array;
                } else {
                    $dumped[$prop] = self::dump($value);
                }
            }
        }
        return $dumped;
    }
}
```

Maybe this can be of any help for you.

Anyway, the way you have structured and open sourced the framework is great. And fitting these models into my small project is really easy. 

best regards, Michael

**Comment by chriskapp** [comment] 2018-08-04 13:09
Hi Michael, thanks for the feedback. Could you show me the complete data structure which you have created with the Swagger models so that I can create a fitting test case for this.

Currently we have also a simple test case for the swagger model at:
https://github.com/apioo/psx-model/blob/master/tests/Swagger/SwaggerTest.php

which uses also the dumper and it seems that the tests are currently working:
https://travis-ci.org/apioo/psx-model

so it would be great to reproduce the problem with these models.

**Comment by mijohansen** [comment] 2018-08-06 06:06
Actually the https://github.com/apioo/psx-model/blob/master/tests/Swagger/SwaggerTest.php testcase breakes. I'm not able to run it with phpunit, but just copied the code and got the same result. I'll reproduce this when I get to my home computer again.

**Comment by chriskapp** [comment] 2018-08-07 17:18
ok, this sounds like the doctrine annotation loader does not work properly. Do you have registered an annotation loader so that doctrine can load the fitting classes i.e.:

```php
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(function ($class) {
    spl_autoload_call($class);
    return class_exists($class, false);
});
```

for the test cases we do this in the `tests/bootstrap.php` so you need to define this as bootstrap for phpunit. Then the tests should work as expected.

**Comment by chriskapp** [comment] 2019-10-26 08:34
I will close this issue since it looks like it is solved

**Closed as completed by chriskapp** 2019-10-26 08:34 UTC
